CREATE (TheMatrix:Movie {title:"The Matrix", released:1999, tagline:"Welcome to the Real World"});
CREATE (Keanu:Person {name:"Keanu Reeves", born:1964});
CREATE (Carrie:Person {name:"Carrie-Anne Moss", born:1967});
CREATE (Laurence:Person {name:"Laurence Fishburne", born: 1961});
CREATE (Hugo:Person {name:"Hugo Weaving", born:1960});
CREATE (LillyW:Person {name:"Lilly Wachowski", born:1967});
CREATE (LanaW:Person {name:"Lana Wachowski", born:1965});
CREATE (JoelS:Person {name:"Joel Silver", born:1952});
CREATE (Keanu)-[:ACTED_IN {role:"Neo"}]->(TheMatrix);
CREATE (Carrie)-[:ACTED_IN {role:"Trinity"}]->(TheMatrix);
CREATE (Laurence)-[:ACTED_IN {role:"Morpheus"}]->(TheMatrix);
CREATE (Hugo)-[:ACTED_IN {role:"Agent Smith"}]->(TheMatrix);
CREATE (LillyW)-[:DIRECTED]->(TheMatrix);
CREATE (LanaW)-[:DIRECTED]->(TheMatrix);
CREATE (JoelS)-[:PRODUCED]->(TheMatrix);
CREATE (Emil:Person {name:"Emil Eifrem", born:1978});
CREATE (Emil)-[:ACTED_IN {role:"Emil"}]->(TheMatrix);

CREATE (TheMatrixReloaded:Movie {title:"The Matrix Reloaded", released:2003, tagline:"Free your mind"});
CREATE (Keanu)-[:ACTED_IN {role:"Neo"}]->(TheMatrixReloaded);
CREATE (Carrie)-[:ACTED_IN {role:"Trinity"}]->(TheMatrixReloaded);
CREATE (Laurence)-[:ACTED_IN {role:"Morpheus"}]->(TheMatrixReloaded);
CREATE (Hugo)-[:ACTED_IN {role:"Agent Smith"}]->(TheMatrixReloaded);
CREATE (LillyW)-[:DIRECTED]->(TheMatrixReloaded);
CREATE (LanaW)-[:DIRECTED]->(TheMatrixReloaded);
CREATE (JoelS)-[:PRODUCED]->(TheMatrixReloaded);

CREATE (TheMatrixRevolutions:Movie {title:"The Matrix Revolutions", released:2003, tagline:"Everything that has a beginning has an end"});
CREATE (Keanu)-[:ACTED_IN {role:"Neo"}]->(TheMatrixRevolutions);
CREATE (Carrie)-[:ACTED_IN {role:"Trinity"}]->(TheMatrixRevolutions);
CREATE (Laurence)-[:ACTED_IN {role:"Morpheus"}]->(TheMatrixRevolutions);
CREATE (Hugo)-[:ACTED_IN {role:"Agent Smith"}]->(TheMatrixRevolutions);
CREATE (LillyW)-[:DIRECTED]->(TheMatrixRevolutions);
CREATE (LanaW)-[:DIRECTED]->(TheMatrixRevolutions);
CREATE (JoelS)-[:PRODUCED]->(TheMatrixRevolutions);

CREATE (TheDevilsAdvocate:Movie {title:"The Devil's Advocate", released: 1997, tagline:"Evil has its winning ways"});
CREATE (Charlize:Person {name:"Charlize Theron", born:1975});
CREATE (Al:Person {name:"Al Pacino", born:1940});
CREATE (Taylor:Person {name:"Taylor Hackford", born:1944});
CREATE (Keanu)-[:ACTED_IN {role:"Kevin Lomax"}]->(TheDevilsAdvocate);
CREATE (Charlize)-[:ACTED_IN {role:"Mary Ann Lomax"}]->(TheDevilsAdvocate);
CREATE (Al)-[:ACTED_IN {role:"John Milton"}]->(TheDevilsAdvocate);
CREATE (Taylor)-[:DIRECTED]->(TheDevilsAdvocate);

CREATE (AFewGoodMen:Movie {title:"A Few Good Men", released:1992, tagline:"In the heart of the nation's capital, in a courthouse of the U.S. government, one man will stop at nothing to keep his honor, and one will stop at nothing to find the truth."});
CREATE (TomC:Person {name:"Tom Cruise", born:1962});
CREATE (JackN:Person {name:"Jack Nicholson", born:1937});
CREATE (DemiM:Person {name:"Demi Moore", born:1962});
CREATE (KevinB:Person {name:"Kevin Bacon", born:1958});
CREATE (KieferS:Person {name:"Kiefer Sutherland", born: 1966});
CREATE (NoahW:Person {name:"Noah Wyle", born:1971});
CREATE (CubaG:Person {name:"Cuba Gooding Jr.", born:1968});
CREATE (KevinP:Person {name:"Kevin Pollak", born:1957});
CREATE (JTW:Person {name:"J.T. Walsh", born:1943});
CREATE (JamesM:Person {name:"James Marshall", born:1967});
CREATE (ChristopherG:Person {name:"Christopher Guest", born:1948});
CREATE (RobR:Person {name:"Rob Reiner", born:1947});
CREATE (AaronS:Person {name:"Aaron Sorkin", born:1961});
CREATE (TomC)-[:ACTED_IN {role:"Lt. Daniel Kaffee"}]->(AFewGoodMen);
CREATE (JackN)-[:ACTED_IN {role:"Col. Nathan R. Jessup"}]->(AFewGoodMen);
CREATE (DemiM)-[:ACTED_IN {role:"Lt. Cdr. JoAnne Galloway"}]->(AFewGoodMen);
CREATE (KevinB)-[:ACTED_IN {role:"Capt. Jack Ross"}]->(AFewGoodMen);
CREATE (KieferS)-[:ACTED_IN {role:"Lt. Jonathan Kendrick"}]->(AFewGoodMen);
CREATE (NoahW)-[:ACTED_IN {role:"Cpl. Jeffrey Barnes"}]->(AFewGoodMen);
CREATE (CubaG)-[:ACTED_IN {role:"Cpl. Carl Hammaker"}]->(AFewGoodMen);
CREATE (KevinP)-[:ACTED_IN {role:"Lt. Sam Weinberg"}]->(AFewGoodMen);
CREATE (JTW)-[:ACTED_IN {role:"Lt. Col. Matthew Andrew Markinson"}]->(AFewGoodMen);
CREATE (JamesM)-[:ACTED_IN {role:"Pfc. Louden Downey"}]->(AFewGoodMen);
CREATE (ChristopherG)-[:ACTED_IN {role:"Dr. Stone"}]->(AFewGoodMen);
CREATE (AaronS)-[:ACTED_IN {role:"Man in Bar"}]->(AFewGoodMen);
CREATE (RobR)-[:DIRECTED]->(AFewGoodMen);
CREATE (AaronS)-[:WROTE]->(AFewGoodMen);

CREATE (TopGun:Movie {title:"Top Gun", released:1986, tagline:"I feel the need, the need for speed."});
CREATE (KellyM:Person {name:"Kelly McGillis", born:1957});
CREATE (ValK:Person {name:"Val Kilmer", born:1959});
CREATE (AnthonyE:Person {name:"Anthony Edwards", born:1962});
CREATE (TomS:Person {name:"Tom Skerritt", born:1933});
CREATE (MegR:Person {name:"Meg Ryan", born:1961});
CREATE (TonyS:Person {name:"Tony Scott", born:1944});
CREATE (JimC:Person {name:"Jim Cash", born:1941});
CREATE (TomC)-[:ACTED_IN {role:"Maverick"}]->(TopGun);
CREATE (KellyM)-[:ACTED_IN {role:"Charlie"}]->(TopGun);
CREATE (ValK)-[:ACTED_IN {role:"Iceman"}]->(TopGun);
CREATE (AnthonyE)-[:ACTED_IN {role:"Goose"}]->(TopGun);
CREATE (TomS)-[:ACTED_IN {role:"Viper"}]->(TopGun);
CREATE (MegR)-[:ACTED_IN {role:"Carole"}]->(TopGun);
CREATE (TonyS)-[:DIRECTED]->(TopGun);
CREATE (JimC)-[:WROTE]->(TopGun);

CREATE (JerryMaguire:Movie {title:"Jerry Maguire", released: 2000, tagline:"The rest of his life begins now."});
CREATE (ReneeZ:Person {name:"Renee Zellweger", born:1969});
CREATE (KellyP:Person {name:"Kelly Preston", born:1962});
CREATE (JerryO:Person {name:"Jerry O'Connell", born:1974});
CREATE (JayM:Person {name:"Jay Mohr", born:1970});
CREATE (BonnieH:Person {name:"Bonnie Hunt", born:1961});
CREATE (ReginaK:Person {name:"Regina King", born:1971});
CREATE (JonathanL:Person {name:"Jonathan Lipnicki", born:1996});
CREATE (CameronC:Person {name:"Cameron Crowe", born:1957});
CREATE (TomC)-[:ACTED_IN {role:"Jerry Maguire"}]->(JerryMaguire);
CREATE (CubaG)-[:ACTED_IN {role:"Rod Tidwell"}]->(JerryMaguire);
CREATE (ReneeZ)-[:ACTED_IN {role:"Dorothy Boyd"}]->(JerryMaguire);
CREATE (KellyP)-[:ACTED_IN {role:"Avery Bishop"}]->(JerryMaguire);
CREATE (JerryO)-[:ACTED_IN {role:"Frank Cushman"}]->(JerryMaguire);
CREATE (JayM)-[:ACTED_IN {role:"Bob Sugar"}]->(JerryMaguire);
CREATE (BonnieH)-[:ACTED_IN {role:"Laurel Boyd"}]->(JerryMaguire);
CREATE (ReginaK)-[:ACTED_IN {role:"Marcee Tidwell"}]->(JerryMaguire);
CREATE (JonathanL)-[:ACTED_IN {role:"Ray Boyd"}]->(JerryMaguire);
CREATE (CameronC)-[:DIRECTED]->(JerryMaguire);
CREATE (CameronC)-[:PRODUCED]->(JerryMaguire);
CREATE (CameronC)-[:WROTE]->(JerryMaguire);

CREATE (StandByMe:Movie {title:"Stand By Me", released:1986, tagline:"For some, it's the last real taste of innocence, and the first real taste of life.  But for everyone, it's the time that memories are made of."});
CREATE (RiverP:Person {name:"River Phoenix", born:1970});
CREATE (CoreyF:Person {name:"Corey Feldman", born:1971});
CREATE (WilW:Person {name:"Wil Wheaton", born: 1972});
CREATE (JohnC:Person {name:"John Cusack", born:1966});
CREATE (MarshallB:Person {name:"Marshall Bell", born:1942});
CREATE (WilW)-[:ACTED_IN {role:"Gordie Lachance"}]->(StandByMe);
CREATE (RiverP)-[:ACTED_IN {role:"Chris Chambers"}]->(StandByMe);
CREATE (JerryO)-[:ACTED_IN {role:"Vern Tessio"}]->(StandByMe);
CREATE (CoreyF)-[:ACTED_IN {role:"Teddy Duchamp"}]->(StandByMe);
CREATE (JohnC)-[:ACTED_IN {role:"Denny Lachance"}]->(StandByMe);
CREATE (KieferS)-[:ACTED_IN {role:"Ace Merrill"}]->(StandByMe);
CREATE (MarshallB)-[:ACTED_IN {role:"Mr. Lachance"}]->(StandByMe);
CREATE (RobR)-[:DIRECTED]->(StandByMe);

CREATE (AsGoodAsItGets:Movie {title:"As Good as It Gets", released:1997, tagline:"A comedy from the heart that goes for the throat."});
CREATE (HelenH:Person {name:"Helen Hunt", born:1963});
CREATE (GregK:Person {name:"Greg Kinnear", born:1963});
CREATE (JamesB:Person {name:"James L. Brooks", born:1940});
CREATE (JackN)-[:ACTED_IN {role:"Melvin Udall"}]->(AsGoodAsItGets);
CREATE (HelenH)-[:ACTED_IN {role:"Carol Connelly"}]->(AsGoodAsItGets);
CREATE (GregK)-[:ACTED_IN {role:"Simon Bishop"}]->(AsGoodAsItGets);
CREATE (CubaG)-[:ACTED_IN {role:"Frank Sachs"}]->(AsGoodAsItGets);
CREATE (JamesB)-[:DIRECTED]->(AsGoodAsItGets);

CREATE (WhatDreamsMayCome:Movie {title:"What Dreams May Come", released:1998, tagline:"After life there is more.  The end is just the beginning."});
CREATE (AnnabellaS:Person {name:"Annabella Sciorra", born:1960});
CREATE (MaxS:Person {name:"Max von Sydow", born:1929});
CREATE (WernerH:Person {name:"Werner Herzog", born:1942});
CREATE (Robin:Person {name:"Robin Williams", born:1951});
CREATE (VincentW:Person {name:"Vincent Ward", born:1956});
CREATE (Robin)-[:ACTED_IN {role:"Chris Nielsen"}]->(WhatDreamsMayCome);
CREATE (CubaG)-[:ACTED_IN {role:"Albert Lewis"}]->(WhatDreamsMayCome);
CREATE (AnnabellaS)-[:ACTED_IN {role:"Annie Collins-Nielsen"}]->(WhatDreamsMayCome);
CREATE (MaxS)-[:ACTED_IN {role:"The Tracker"}]->(WhatDreamsMayCome);
CREATE (WernerH)-[:ACTED_IN {role:"The Face"}]->(WhatDreamsMayCome);
CREATE (VincentW)-[:DIRECTED]->(WhatDreamsMayCome);

CREATE (SnowFallingonCedars:Movie {title:"Snow Falling on Cedars", released: 1999, tagline:"First loves last.  Forever."});
CREATE (EthanH:Person {name:"Ethan Hawke", born: 1970});
CREATE (RickY:Person {name:"Rick Yune", born:1971});
CREATE (JamesC:Person {name:"James Cromwell", born:1940});
CREATE (ScottH:Person {name:"Scott Hicks", born:1953});
CREATE (EthanH)-[:ACTED_IN {role:"Ishmael Chambers"}]->(SnowFallingonCedars);
CREATE (RickY)-[:ACTED_IN {role:"Kazuo Miyamoto"}]->(SnowFallingonCedars);
CREATE (MaxS)-[:ACTED_IN {role:"Nels Gudmundsson"}]->(SnowFallingonCedars);
CREATE (JamesC)-[:ACTED_IN {role:"Judge Fielding"}]->(SnowFallingonCedars);
CREATE (ScottH)-[:DIRECTED]->(SnowFallingonCedars);

CREATE (YouveGotMail:Movie {title:"You've Got Mail", released:1998, tagline:"At odds in life...  in love on-line."});
CREATE (ParkerP:Person {name:"Parker Posey", born:1968});
CREATE (DaveC:Person {name:"Dave Chappelle", born:1973});
CREATE (SteveZ:Person {name:"Steve Zahn", born:1967});
CREATE (TomH:Person {name:"Tom Hanks", born:1956});
CREATE (NoraE:Person {name:"Nora Ephron", born:1941});
CREATE (TomH)-[:ACTED_IN {role:"Joe Fox"}]->(YouveGotMail);
CREATE (MegR)-[:ACTED_IN {role:"Kathleen Kelly"}]->(YouveGotMail);
CREATE (GregK)-[:ACTED_IN {role:"Frank Navasky"}]->(YouveGotMail);
CREATE (ParkerP)-[:ACTED_IN {role:"Patricia Eden"}]->(YouveGotMail);
CREATE (DaveC)-[:ACTED_IN {role:"Kevin Jackson"}]->(YouveGotMail);
CREATE (SteveZ)-[:ACTED_IN {role:"George Pappas"}]->(YouveGotMail);
CREATE (NoraE)-[:DIRECTED]->(YouveGotMail);

CREATE (SleeplessInSeattle:Movie {title:"Sleepless in Seattle", released:1993, tagline:"What if someone you never met, someone you never saw, someone you never knew was the only someone for you?"});
CREATE (RitaW:Person {name:"Rita Wilson", born:1956});
CREATE (BillPull:Person {name:"Bill Pullman", born:1953});
CREATE (VictorG:Person {name:"Victor Garber", born:1949});
CREATE (RosieO:Person {name:"Rosie O'Donnell", born:1962});
CREATE (TomH)-[:ACTED_IN {role:"Sam Baldwin"}]->(SleeplessInSeattle);
CREATE (MegR)-[:ACTED_IN {role:"Annie Reed"}]->(SleeplessInSeattle);
CREATE (RitaW)-[:ACTED_IN {role:"Suzy"}]->(SleeplessInSeattle);
CREATE (BillPull)-[:ACTED_IN {role:"Walter"}]->(SleeplessInSeattle);
CREATE (VictorG)-[:ACTED_IN {role:"Greg"}]->(SleeplessInSeattle);
CREATE (RosieO)-[:ACTED_IN {role:"Becky"}]->(SleeplessInSeattle);
CREATE (NoraE)-[:DIRECTED]->(SleeplessInSeattle);

CREATE (JoeVersustheVolcano:Movie {title:"Joe Versus the Volcano", released:1990, tagline:"A story of love, lava and burning desire."});
CREATE (JohnS:Person {name:"John Patrick Stanley", born:1950});
CREATE (Nathan:Person {name:"Nathan Lane", born:1956});
CREATE (TomH)-[:ACTED_IN {role:"Joe Banks"}]->(JoeVersustheVolcano);
CREATE (MegR)-[:ACTED_IN {role:"DeDe"}]->(JoeVersustheVolcano);
CREATE (Nathan)-[:ACTED_IN {role:"Baw"}]->(JoeVersustheVolcano);
CREATE (JohnS)-[:DIRECTED]->(JoeVersustheVolcano);

CREATE (WhenHarryMetSally:Movie {title:"When Harry Met Sally", released:1998, tagline:"Can two friends sleep together and still love each other in the morning?"});
CREATE (BillyC:Person {name:"Billy Crystal", born:1948});
CREATE (CarrieF:Person {name:"Carrie Fisher", born:1956});
CREATE (BrunoK:Person {name:"Bruno Kirby", born:1949});
CREATE (BillyC)-[:ACTED_IN {role:"Harry Burns"}]->(WhenHarryMetSally);
CREATE (MegR)-[:ACTED_IN {role:"Sally Albright"}]->(WhenHarryMetSally);
CREATE (CarrieF)-[:ACTED_IN {role:"Marie"}]->(WhenHarryMetSally);
CREATE (BrunoK)-[:ACTED_IN {role:"Jess"}]->(WhenHarryMetSally);
CREATE (RobR)-[:DIRECTED]->(WhenHarryMetSally);
CREATE (RobR)-[:PRODUCED]->(WhenHarryMetSally);
CREATE (NoraE)-[:PRODUCED]->(WhenHarryMetSally);
CREATE (NoraE)-[:WROTE]->(WhenHarryMetSally);

CREATE (ThatThingYouDo:Movie {title:"That Thing You Do", released:1996, tagline:"In every life there comes a time when that thing you dream becomes that thing you do"});
CREATE (LivT:Person {name:"Liv Tyler", born:1977});
CREATE (TomH)-[:ACTED_IN {role:"Mr. White"}]->(ThatThingYouDo);
CREATE (LivT)-[:ACTED_IN {role:"Faye Dolan"}]->(ThatThingYouDo);
CREATE (Charlize)-[:ACTED_IN {role:"Tina"}]->(ThatThingYouDo);
CREATE (TomH)-[:DIRECTED]->(ThatThingYouDo);

CREATE (TheReplacements:Movie {title:"The Replacements", released:2000, tagline:"Pain heals, Chicks dig scars...  Glory lasts forever"});
CREATE (Brooke:Person {name:"Brooke Langton", born:1970});
CREATE (Gene:Person {name:"Gene Hackman", born:1930});
CREATE (Orlando:Person {name:"Orlando Jones", born:1968});
CREATE (Howard:Person {name:"Howard Deutch", born:1950});
CREATE (Keanu)-[:ACTED_IN {role:"Shane Falco"}]->(TheReplacements);
CREATE (Brooke)-[:ACTED_IN {role:"Annabelle Farrell"}]->(TheReplacements);
CREATE (Gene)-[:ACTED_IN {role:"Jimmy McGinty"}]->(TheReplacements);
CREATE (Orlando)-[:ACTED_IN {role:"Clifford Franklin"}]->(TheReplacements);
CREATE (Howard)-[:DIRECTED]->(TheReplacements);

CREATE (RescueDawn:Movie {title:"RescueDawn", released:2006, tagline:"Based on the extraordinary true story of one man's fight for freedom"});
CREATE (ChristianB:Person {name:"Christian Bale", born:1974});
CREATE (ZachG:Person {name:"Zach Grenier", born:1954});
CREATE (MarshallB)-[:ACTED_IN {role:"Admiral"}]->(RescueDawn);
CREATE (ChristianB)-[:ACTED_IN {role:"Dieter Dengler"}]->(RescueDawn);
CREATE (ZachG)-[:ACTED_IN {role:"Squad Leader"}]->(RescueDawn);
CREATE (SteveZ)-[:ACTED_IN {role:"Duane"}]->(RescueDawn);
CREATE (WernerH)-[:DIRECTED]->(RescueDawn);

CREATE (TheBirdcage:Movie {title:"The Birdcage", released:1996, tagline:"Come as you are"});
CREATE (MikeN:Person {name:"Mike Nichols", born:1931});
CREATE (Robin)-[:ACTED_IN {role:"Armand Goldman"}]->(TheBirdcage);
CREATE (Nathan)-[:ACTED_IN {role:"Albert Goldman"}]->(TheBirdcage);
CREATE (Gene)-[:ACTED_IN {role:"Sen. Kevin Keeley"}]->(TheBirdcage);
CREATE (MikeN)-[:DIRECTED]->(TheBirdcage);

CREATE (Unforgiven:Movie {title:"Unforgiven", released:1992, tagline:"It's a hell of a thing, killing a man"});
CREATE (RichardH:Person {name:"Richard Harris", born:1930});
CREATE (ClintE:Person {name:"Clint Eastwood", born:1930});
CREATE (RichardH)-[:ACTED_IN {role:"English Bob"}]->(Unforgiven);
CREATE (ClintE)-[:ACTED_IN {role:"Bill Munny"}]->(Unforgiven);
CREATE (Gene)-[:ACTED_IN {role:"Little Bill Daggett"}]->(Unforgiven);
CREATE (ClintE)-[:DIRECTED]->(Unforgiven);

CREATE (JohnnyMnemonic:Movie {title:"Johnny Mnemonic", released:1995, tagline:"The hottest data on earth.  In the coolest head in town"});
CREATE (Takeshi:Person {name:"Takeshi Kitano", born:1947});
CREATE (Dina:Person {name:"Dina Meyer", born:1968});
CREATE (IceT:Person {name:"Ice-T", born:1958});
CREATE (RobertL:Person {name:"Robert Longo", born:1953});
CREATE (Keanu)-[:ACTED_IN {role:"Johnny Mnemonic"}]->(JohnnyMnemonic);
CREATE (Takeshi)-[:ACTED_IN {role:"Takahashi"}]->(JohnnyMnemonic);
CREATE (Dina)-[:ACTED_IN {role:"Jane"}]->(JohnnyMnemonic);
CREATE (IceT)-[:ACTED_IN {role:"J-Bone"}]->(JohnnyMnemonic);
CREATE (RobertL)-[:DIRECTED]->(JohnnyMnemonic);

CREATE (CloudAtlas:Movie {title:"Cloud Atlas", released:2012, tagline:"Everything is connected"});
CREATE (HalleB:Person {name:"Halle Berry", born:1966});
CREATE (JimB:Person {name:"Jim Broadbent", born:1949});
CREATE (TomT:Person {name:"Tom Tykwer", born:1965});
CREATE (DavidMitchell:Person {name:"David Mitchell", born:1969});
CREATE (StefanArndt:Person {name:"Stefan Arndt", born:1961});
CREATE (TomH)-[:ACTED_IN {role:"Zachry"}]->(CloudAtlas);
CREATE (Hugo)-[:ACTED_IN {role:"Bill Smoke"}]->(CloudAtlas);
CREATE (HalleB)-[:ACTED_IN {role:"Luisa Rey"}]->(CloudAtlas);
CREATE (JimB)-[:ACTED_IN {role:"Vyvyan Ayrs"}]->(CloudAtlas);
CREATE (TomT)-[:DIRECTED]->(CloudAtlas);
CREATE (LillyW)-[:DIRECTED]->(CloudAtlas);
CREATE (LanaW)-[:DIRECTED]->(CloudAtlas);
CREATE (DavidMitchell)-[:WROTE]->(CloudAtlas);
CREATE (StefanArndt)-[:PRODUCED]->(CloudAtlas);

CREATE (TheDaVinciCode:Movie {title:"The Da Vinci Code", released: 2006, tagline:"Break The Codes"});
CREATE (IanM:Person {name:"Ian McKellen", born:1939});
CREATE (AudreyT:Person {name:"Audrey Tautou", born:1976});
CREATE (PaulB:Person {name:"Paul Bettany", born:1971});
CREATE (RonH:Person {name:"Ron Howard", born:1954});
CREATE (TomH)-[:ACTED_IN {role:"Dr. Robert Langdon"}]->(TheDaVinciCode);
CREATE (IanM)-[:ACTED_IN {role:"Sir Leight Teabing"}]->(TheDaVinciCode);
CREATE (AudreyT)-[:ACTED_IN {role:"Sophie Neveu"}]->(TheDaVinciCode);
CREATE (PaulB)-[:ACTED_IN {role:"Silas"}]->(TheDaVinciCode);
CREATE (RonH)-[:DIRECTED]->(TheDaVinciCode);

CREATE (VforVendetta:Movie {title:"V for Vendetta", released:2006, tagline:"Freedom!  Forever!"});
CREATE (NatalieP:Person {name:"Natalie Portman", born:1981});
CREATE (StephenR:Person {name:"Stephen Rea", born:1946});
CREATE (JohnH:Person {name:"John Hurt", born:1940});
CREATE (BenM:Person {name:  "Ben Miles", born: 1967});
CREATE (Hugo)-[:ACTED_IN {role:"V"}]->(VforVendetta);
CREATE (NatalieP)-[:ACTED_IN {role:"Evey Hammond"}]->(VforVendetta);
CREATE (StephenR)-[:ACTED_IN {role:"Eric Finch"}]->(VforVendetta);
CREATE (JohnH)-[:ACTED_IN {role:"High Chancellor Adam Sutler"}]->(VforVendetta);
CREATE (BenM)-[:ACTED_IN {role:"Dascomb"}]->(VforVendetta);
CREATE (JamesM)-[:DIRECTED]->(VforVendetta);
CREATE (LillyW)-[:PRODUCED]->(VforVendetta);
CREATE (LanaW)-[:PRODUCED]->(VforVendetta);
CREATE (JoelS)-[:PRODUCED]->(VforVendetta);
CREATE (LillyW)-[:WROTE]->(VforVendetta);
CREATE (LanaW)-[:WROTE]->(VforVendetta);

CREATE (SpeedRacer:Movie {title:"Speed Racer", released:2008, tagline:"Speed has no limits"});
CREATE (EmileH:Person {name:"Emile Hirsch", born:1985});
CREATE (JohnG:Person {name:"John Goodman", born:1960});
CREATE (SusanS:Person {name:"Susan Sarandon", born:1946});
CREATE (MatthewF:Person {name:"Matthew Fox", born:1966});
CREATE (ChristinaR:Person {name:"Christina Ricci", born:1980});
CREATE (Rain:Person {name:"Rain", born: 1982});
CREATE (EmileH)-[:ACTED_IN {role:"Speed Racer"}]->(SpeedRacer);
CREATE (JohnG)-[:ACTED_IN {role:"Pops"}]->(SpeedRacer);
CREATE (SusanS)-[:ACTED_IN {role:"Mom"}]->(SpeedRacer);
CREATE (MatthewF)-[:ACTED_IN {role:"Racer X"}]->(SpeedRacer);
CREATE (ChristinaR)-[:ACTED_IN {role:"Trixie"}]->(SpeedRacer);
CREATE (Rain)-[:ACTED_IN {role:"Taejo Togokahn"}]->(SpeedRacer);
CREATE (BenM)-[:ACTED_IN {role:"Cass Jones"}]->(SpeedRacer);
CREATE (LillyW)-[:DIRECTED]->(SpeedRacer);
CREATE (LanaW)-[:DIRECTED]->(SpeedRacer);
CREATE (LillyW)-[:WROTE]->(SpeedRacer);
CREATE (LanaW)-[:WROTE]->(SpeedRacer);
CREATE (JoelS)-[:PRODUCED]->(SpeedRacer);

CREATE (NinjaAssassin:Movie {title:"Ninja Assassin", released:2009, tagline:"Prepare to enter a secret world of assassins"});
CREATE (NaomieH:Person {name:"Naomie Harris"});
CREATE (Rain)-[:ACTED_IN {role:"Raizo"}]->(NinjaAssassin);
CREATE (NaomieH)-[:ACTED_IN {role:"Mika Coretti"}]->(NinjaAssassin);
CREATE (RickY)-[:ACTED_IN {role:"Takeshi"}]->(NinjaAssassin);
CREATE (BenM)-[:ACTED_IN {role:"Ryan Maslow"}]->(NinjaAssassin);
CREATE (JamesM)-[:DIRECTED]->(NinjaAssassin);
CREATE (LillyW)-[:PRODUCED]->(NinjaAssassin);
CREATE (LanaW)-[:PRODUCED]->(NinjaAssassin);
CREATE (JoelS)-[:PRODUCED]->(NinjaAssassin);

CREATE (TheGreenMile:Movie {title:"The Green Mile", released:1999, tagline:"Walk a mile you'll never forget."});
CREATE (MichaelD:Person {name:"Michael Clarke Duncan", born:1957});
CREATE (DavidM:Person {name:"David Morse", born:1953});
CREATE (SamR:Person {name:"Sam Rockwell", born:1968});
CREATE (GaryS:Person {name:"Gary Sinise", born:1955});
CREATE (PatriciaC:Person {name:"Patricia Clarkson", born:1959});
CREATE (FrankD:Person {name:"Frank Darabont", born:1959});
CREATE (TomH)-[:ACTED_IN {role:"Paul Edgecomb"}]->(TheGreenMile);
CREATE (MichaelD)-[:ACTED_IN {role:"John Coffey"}]->(TheGreenMile);
CREATE (DavidM)-[:ACTED_IN {role:"Brutus 'Brutal' Howell"}]->(TheGreenMile);
CREATE (BonnieH)-[:ACTED_IN {role:"Jan Edgecomb"}]->(TheGreenMile);
CREATE (JamesC)-[:ACTED_IN {role:"Warden Hal Moores"}]->(TheGreenMile);
CREATE (SamR)-[:ACTED_IN {role: "'Wild Bill' Wharton"}]->(TheGreenMile);
CREATE (GaryS)-[:ACTED_IN {role:"Burt Hammersmith"}]->(TheGreenMile);
CREATE (PatriciaC)-[:ACTED_IN {role:"Melinda Moores"}]->(TheGreenMile);
CREATE (FrankD)-[:DIRECTED]->(TheGreenMile);

CREATE (FrostNixon:Movie {title:"Frost/Nixon", released:2008, tagline:"400 million people were waiting for the truth."});
CREATE (FrankL:Person {name:"Frank Langella", born:1938});
CREATE (MichaelS:Person {name:"Michael Sheen", born:1969});
CREATE (OliverP:Person {name:"Oliver Platt", born:1960});
CREATE (FrankL)-[:ACTED_IN {role:"Richard Nixon"}]->(FrostNixon);
CREATE (MichaelS)-[:ACTED_IN {role:"David Frost"}]->(FrostNixon);
CREATE (KevinB)-[:ACTED_IN {role:"Jack Brennan"}]->(FrostNixon);
CREATE (OliverP)-[:ACTED_IN {role:"Bob Zelnick"}]->(FrostNixon);
CREATE (SamR)-[:ACTED_IN {role:"James Reston, Jr."}]->(FrostNixon);
CREATE (RonH)-[:DIRECTED]->(FrostNixon);

CREATE (Hoffa:Movie {title:"Hoffa", released:1992, tagline:"He didn't want law.  He wanted justice."});
CREATE (DannyD:Person {name:"Danny DeVito", born:1944});
CREATE (JohnR:Person {name:"John C. Reilly", born:1965});
CREATE (JackN)-[:ACTED_IN {role:"Hoffa"}]->(Hoffa);
CREATE (DannyD)-[:ACTED_IN {role:"Robert 'Bobby' Ciaro"}]->(Hoffa);
CREATE (JTW)-[:ACTED_IN {role:"Frank Fitzsimmons"}]->(Hoffa);
CREATE (JohnR)-[:ACTED_IN {role:"Peter 'Pete' Connelly"}]->(Hoffa);
CREATE (DannyD)-[:DIRECTED]->(Hoffa);

CREATE (Apollo13:Movie {title:"Apollo 13", released:1995, tagline:"Houston, we have a problem."});
CREATE (EdH:Person {name:"Ed Harris", born:1950});
CREATE (BillPax:Person {name:"Bill Paxton", born:1955});
CREATE (TomH)-[:ACTED_IN {role:"Jim Lovell"}]->(Apollo13);
CREATE (KevinB)-[:ACTED_IN {role:"Jack Swigert"}]->(Apollo13);
CREATE (EdH)-[:ACTED_IN {role:"Gene Kranz"}]->(Apollo13);
CREATE (BillPax)-[:ACTED_IN {role:"Fred Haise"}]->(Apollo13);
CREATE (GaryS)-[:ACTED_IN {role:"Ken Mattingly"}]->(Apollo13);
CREATE (RonH)-[:DIRECTED]->(Apollo13);

CREATE (Twister:Movie {title:"Twister", released:1996, tagline:"Don't Breathe.  Don't Look Back."});
CREATE (PhilipH:Person {name:"Philip Seymour Hoffman", born:1967});
CREATE (JanB:Person {name:"Jan de Bont", born:1943});
CREATE (BillPax)-[:ACTED_IN {role:"Bill Harding"}]->(Twister);
CREATE (HelenH)-[:ACTED_IN {role:"Dr. Jo Harding"}]->(Twister);
CREATE (ZachG)-[:ACTED_IN {role:"Eddie"}]->(Twister);
CREATE (PhilipH)-[:ACTED_IN {role:"Dustin 'Dusty' Davis"}]->(Twister);
CREATE (JanB)-[:DIRECTED]->(Twister);

CREATE (CastAway:Movie {title:"Cast Away", released:2000, tagline:"At the edge of the world, his journey begins."});
CREATE (RobertZ:Person {name:"Robert Zemeckis", born:1951});
CREATE (TomH)-[:ACTED_IN {role:"Chuck Noland"}]->(CastAway);
CREATE (HelenH)-[:ACTED_IN {role:"Kelly Frears"}]->(CastAway);
CREATE (RobertZ)-[:DIRECTED]->(CastAway);

CREATE (OneFlewOvertheCuckoosNest:Movie {title:"One Flew Over the Cuckoo's Nest", released:1975, tagline:"If he's crazy, what does that make you?"});
CREATE (MilosF:Person {name:"Milos Forman", born:1932});
CREATE (JackN)-[:ACTED_IN {role:"Randle McMurphy"}]->(OneFlewOvertheCuckoosNest);
CREATE (DannyD)-[:ACTED_IN {role:"Martini"}]->(OneFlewOvertheCuckoosNest);
CREATE (MilosF)-[:DIRECTED]->(OneFlewOvertheCuckoosNest);

CREATE (SomethingsGottaGive:Movie {title:"Something's Gotta Give", released: 2003});
CREATE (DianeK:Person {name:"Diane Keaton", born:1946});
CREATE (NancyM:Person {name:"Nancy Meyers", born:1949});
CREATE (JackN)-[:ACTED_IN {role:"Harry Sanborn"}]->(SomethingsGottaGive);
CREATE (DianeK)-[:ACTED_IN {role:"Erica Barry"}]->(SomethingsGottaGive);
CREATE (Keanu)-[:ACTED_IN {role:"Julian Mercer"}]->(SomethingsGottaGive);
CREATE (NancyM)-[:DIRECTED]->(SomethingsGottaGive);
CREATE (NancyM)-[:PRODUCED]->(SomethingsGottaGive);
CREATE (NancyM)-[:WROTE]->(SomethingsGottaGive);

CREATE (BicentennialMan:Movie {title:"Bicentennial Man", released: 1999, tagline:"One robot's 200 year journey to become an ordinary man."});
CREATE (ChrisC:Person {name:"Chris Columbus", born:1958});
CREATE (Robin)-[:ACTED_IN {role:"Andrew Marin"}]->(BicentennialMan);
CREATE (OliverP)-[:ACTED_IN {role:"Rupert Burns"}]->(BicentennialMan);
CREATE (ChrisC)-[:DIRECTED]->(BicentennialMan);

CREATE (CharlieWilsonsWar:Movie {title:"Charlie Wilson's War", released:2007, tagline:"A stiff drink.  A little mascara. A lot of nerve.  Who said they couldn't bring down the Soviet empire."});
CREATE (JuliaR:Person {name:"Julia Roberts", born:1967});
CREATE (TomH)-[:ACTED_IN {role:"Rep. Charlie Wilson"}]->(CharlieWilsonsWar);
CREATE (JuliaR)-[:ACTED_IN {role:"Joanne Herring"}]->(CharlieWilsonsWar);
CREATE (PhilipH)-[:ACTED_IN {role:"Gust Avrakotos"}]->(CharlieWilsonsWar);
CREATE (MikeN)-[:DIRECTED]->(CharlieWilsonsWar);

CREATE (ThePolarExpress:Movie {title:"The Polar Express", released:2004, tagline:"This Holiday Season...  Believe"});
CREATE (TomH)-[:ACTED_IN {role:"Hero Boy"}]->(ThePolarExpress);
CREATE (RobertZ)-[:DIRECTED]->(ThePolarExpress);

CREATE (ALeagueofTheirOwn:Movie {title:"A League of Their Own", released:1992, tagline:"Once in a lifetime you get a chance to do something different."});
CREATE (Madonna:Person {name:"Madonna", born:1954});
CREATE (GeenaD:Person {name:"Geena Davis", born:1956});
CREATE (LoriP:Person {name:"Lori Petty", born:1963});
CREATE (PennyM:Person {name:"Penny Marshall", born:1943});
CREATE (TomH)-[:ACTED_IN {role:"Jimmy Dugan"}]->(ALeagueofTheirOwn);
CREATE (GeenaD)-[:ACTED_IN {role:"Dottie Hinson"}]->(ALeagueofTheirOwn);
CREATE (LoriP)-[:ACTED_IN {role:"Kit Keller"}]->(ALeagueofTheirOwn);
CREATE (RosieO)-[:ACTED_IN {role:"Doris Murphy"}]->(ALeagueofTheirOwn);
CREATE (Madonna)-[:ACTED_IN {role: "'All the Way' Mae Mordabito"}]->(ALeagueofTheirOwn);
CREATE (BillPax)-[:ACTED_IN {role:"Bob Hinson"}]->(ALeagueofTheirOwn);
CREATE (PennyM)-[:DIRECTED]->(ALeagueofTheirOwn);

CREATE (PaulBlythe:Person {name:"Paul Blythe"});
CREATE (AngelaScope:Person {name:"Angela Scope"});
CREATE (JessicaThompson:Person {name:"Jessica Thompson"});
CREATE (JamesThompson:Person {name:"James Thompson"});
CREATE (JamesThompson)-[:FOLLOWS]->(JessicaThompson);
CREATE (AngelaScope)-[:FOLLOWS]->(JessicaThompson);
CREATE (PaulBlythe)-[:FOLLOWS]->(AngelaScope);
CREATE (JessicaThompson)-[:REVIEWED {summary:"An amazing journey", rating: 95}]->(CloudAtlas);
CREATE (JessicaThompson)-[:REVIEWED {summary:"Silly, but fun", rating:65}]->(TheReplacements);
CREATE (JamesThompson)-[:REVIEWED {summary:"The coolest football movie ever", rating:100}]->(TheReplacements);
CREATE (AngelaScope)-[:REVIEWED {summary:"Pretty funny at times", rating:62}]->(TheReplacements);
CREATE (JessicaThompson)-[:REVIEWED {summary:"Dark, but compelling", rating:85}]->(Unforgiven);
CREATE (JessicaThompson)-[:REVIEWED {summary:"Slapstick redeemed only by the Robin Williams and Gene Hackman's stellar performances", rating:45}]->(TheBirdcage);
CREATE (JessicaThompson)-[:REVIEWED {summary:"A solid romp", rating:68}]->(TheDaVinciCode);
CREATE (JamesThompson)-[:REVIEWED {summary:"Fun, but a little far fetched", rating:65}]->(TheDaVinciCode);
CREATE (JessicaThompson)-[:REVIEWED {summary:"You had me at Jerry", rating:92}]->(JerryMaguire);